Fix exception on launch
  Launching results in a failure with the following error message:

  > gi.RepositoryError: Requiring namespace 'Gtk' version '3.0',
  > but '4.0' is already loaded

  This patch explicitly requires GTK version 3.0 before importing it,
  which resolves the issue.